baseurl                 = "www.eli-rodriguez.com/"               # Your domain name. Must end with "/"
languageCode            = "es-es"
defaultContentLanguage  = "es"
isMultilingual          = true
title                   = "Eli Rodríguez Pérez"
theme                   = "sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
publishDir              = "docs"

[params]
    dateform            = "Sat Nov 17 2018 10:50:00 CMT+1"
    dateformfull        = "Sat Nov 17 2018 10:50:00 CMT+1"
    favicon             = "sam.ico"
    homepage            = "Home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    smallPreviewImages   = false                         # Show small images from the subfolder instead of the big versions in the gallery
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # The subfolder for the small versions of the images under the gallery (with trailing slash)
                                                         # For each image the small version has to have the same filename as the big version.
    footerText          = "Elizabeth Rodríguez Pérez | [Instagram](https://instagram.com/eli.seven7) | [Twitter](https://twitter.com/elirp95)"

# Metadata
    description         = "Elizabeth Rodríguez Pérez - programadora, fotógrafa y activista LGTB."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/posts"
    text = "Artículos"

[[params.mainMenu]]
    link = "/gallery"
    text = "Fotografía"
[[params.mainMenu]]
    link = "/about"
    text = "About me!"
